<!DOCTYPE html>
<html>
<head>
    <title><?= $data['title'] ?></title>
    <meta name="description" content="<?= $data['description'] ?>"/>
    <meta name="keywords" content="<?= $data['keywords'] ?>"/>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css2" rel="stylesheet"
          integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link href="css/style.css" rel="stylesheet" type="text/css"/>
    <link rel="icon" href="favicon.ico" type="image/x-icon"/>
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon"/>
</head>

<body>
<div id="wrapper">

    <div id="banner">
        <div id="banner_left">
            <h1>Центр Восстановления Данных</h1>

            <h2>Восстанавливаем данных с HDD, SSD, Flash-накопителей.<br>Восстановление данных с RAID массивов.</h2>
        </div>
        <div id="contactInfo">
            <div id="cont"><span id="phone">(067) 557-88-57<br>(095) 432-00-06</span><br><span id="skype">Skype:<br>Datarec-Ukraine</span></div>
            <div id="address">г. Харьков, пр. Ленина 48,<br> магазин Enter<br>(м.&nbsp;Ботанический сад)</div>
        </div>
    </div>

    <nav id="horizontal">
        <ul id="nav">
            <li><a href="http://www.datarec.com.ua/index.html">главная</a></li>
            <li><a href="news.html">новости</a></li>
            <li><a href="articles.html">статьи</a></li>
            <li><a href="certificates.html">патент</a></li>
            <li><a href="service.html">СЕРВИС</a></li>
            <li><a href="price.html">Цены</a></li>
            <li><a href="photo.html">Фотогалерея</a></li>
            <li><a href="contacts.html">контакты</a></li>
        </ul>
    </nav>

    <div id="rightcol">

        <?php

        //если находимся в разделе статьи
        if ($data['id'] == 3 || ($data['id'] >= 10 && $data['id'] < 20)) {
            echo '<h2> Последние статьи </h2>';

            $path = 'articles/articles_table.txt';
            if (!file_exists($path)) {
                echo '<p>Пока статей нет.</p>';
            } else {
                //выводим список статей в правой колонке
                $lines = array_map('rtrim', file($path));
                $count = count($lines);
                foreach ($lines as $line):
                    printf('<p class ="left"><a href="article%u.html">%s</a></p>', $count, $line);
                    $count--;
                endforeach;

            };
        }
        ?>
        <img class="devider"/>
        <p>Бесплатная доставка изделий в сервисный центр:</p>
        <form id="contacts" action="delivery.php" method="post" onsubmit="return send_message(this);">

            <div><input class="delivery" placeholder="Ваше имя *"></div>
            <div><input class="delivery" placeholder="Телефон *"></div>
            <div><input class="delivery" type="text" name="mail" placeholder="e-mail"></div>
            <div><textarea class="delivery" name="text" rows="6" placeholder="Комментарий"></textarea></div>
            <div><input type="submit" name="submit" value="Вызвать курьера"></div>
        </form>
        <img class="devider"/>

        <h2>Наши магазины</h2>

        <p><span class="fontLarge">Магазин <span class="enter">Enter</span></span><br>
            <a href="http://www.enter.biz.ua/">Компьютеры, комплектующие, ноутбуки, Hi-Fi аппаратура, цифровые
                фотоаппараты, оргтехника и т.д.</p>
        <img src="img/enterbaner.jpg" width="265"
             alt="Компьютеры, комплектующие, ноутбуки, Hi-Fi аппаратура, цифровые фотоаппараты, оргтехника и т.д."/></a>
        <img class="devider"/>

        <p><span class="fontLarge">Магазин <span class="server">СЕРВЕР</span></span><br>
            <a href="http://server.kh.ua/">Оптово-розничная торговля компьютерной техникой</p>
        <img src="img/serverbaner.jpg" height="50" width="260"
             alt="Оптово-розничная торговля компьютерной техникой"/></a>
        <img class="devider"/>

        <p><span class="fontLarge">Компания <span class="dclink">DC-LINK</span></span><br>
            <a href="http://dclink.com.ua/">компьютеры, комплектующие, сети, цифровая техника</p>
        <img src="img/dclink54.png" height="50" width="100"
             alt="компьютеры, комплектующие, сети, цифровая техника"/></a>
        <img class="devider"/>


        <p><span class="fontLarge">Интернет-магазин <span class="cobra">Cobra</span></span><br>
            <a href="http://cobra.com.ua/">компьютеры и комплектующие</p>
        <img src="img/cobra54.png" height="50" width="265"
             alt="компьютеры и комплектующие"/></a>
        <img class="devider"/>

        <br>

    </div>

    <div id="content">
        <?= $data['content']; ?>
    </div>

    <div class="clearfix"></div>
    <footer>
        <p>Логотипы, торговые марки и прочие зарегистрированные знаки принадлежат их правообладателям.
            <br>
            Использование любых материалов, размещённых на сайте, разрешается при условии ссылки на www.datarec.com.ua.<br>
            © 2009 - <?= date('Y') ?>, центр восстановления данных Enter-service.
        </p>
    </footer>
    <div id="counters">
        <noindex>
            <script>
                (function (i, s, o, g, r, a, m) {
                    i['GoogleAnalyticsObject'] = r;
                    i[r] = i[r] || function () {
                            (i[r].q = i[r].q || []).push(arguments)
                        }, i[r].l = 1 * new Date();
                    a = s.createElement(o),
                        m = s.getElementsByTagName(o)[0];
                    a.async = 1;
                    a.src = g;
                    m.parentNode.insertBefore(a, m)
                })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

                ga('create', 'UA-28745264-1', 'auto');
                ga('send', 'pageview');

            </script>
        </noindex>
    </div>

</div>
<script src="scripts/jquery.min.js"></script>
<script src="scripts/scripts.js"></script>
</body>
</html>